# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f0cce0b48f7fac0bb823764b1e655888e6d27ededf7468868d2cca8ace66220d3dff3b6c2e21d84e9e7af7cc5e8b16d25662d07e4460296a886a9dcfb9b211a

test:
  secret_key_base: 79919dcc6472cdcf2e4ee2e19e91b44da37cce6f04e05480e547c030b99d27ba075d3820b4134dca6eeb536c8e2f171c839bfb94cd54677accd5be825c70141a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
