# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e836955ba77e2126d359d9643c506a913b80d13ea03d71aa2e57ff4ad7360bcdf8e3683760ad7c431c905163523503675c2be7a313ee394116e749931e89e542

test:
  secret_key_base: 9d440ca7a49ae54ad32c28c711f835103a7b5622aefef1fbe0ba123f273c91f66d02f000532a6d6a35056c4bb223ed6e9e9a269f470636d14f770c0cac2bf3b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
